In [1]:
import pandas as pd

In [4]:
## 데이터의 값이 한글이 경우 인코딩을 형식을 CP949로 변경
pd.read_csv("../csv/주민등록.csv", encoding='CP949')

,자치구코드(atdrc_code_se),자치구명(atdrc_nm),년월(년월),총인구수(tot_popltn_co),세대수(tot_hshld_co),세대당인구(hshld_popltn_avrg_co),남자인구수(male_popltn_co),여자인구수(female_popltn_co),적재일시(ldadng_dt)
0,금천구,11110,201907,228755,171426,2.44,319062,118352,2018-01-05 16:52:25
1,서대문구,11290,201607,153780,186744,2.12,75614,116393,2018-12-05 10:20:57
2,양천구,11740,201804,594315,61091,2.22,192817,307237,2020-11-03 10:50:11
3,은평구,11200,202004,345156,168865,2.13,229690,204108,2018-01-05 16:52:25
4,마포구,11260,201902,394788,168482,2.52,61714,146951,2018-01-05 16:52:25
5,도봉구,11350,201704,150732,61069,2.39,60735,199831,2018-01-05 16:52:25
6,강북구,11410,202008,404501,174263,2.25,184053,172995,2018-01-05 16:52:25
7,용산구,11620,201407,433658,173943,1.85,252383,198754,2018-01-05 16:52:25
8,관악구,11140,201710,308087,180747,2.01,192923,245902,2021-01-21 15:43:29
9,동대문구,11470,201806,447667,162606,2.49,215440,64221,2020-07-22 20:11:55
10,양천구,11200,201504,559697,109708,2.36,237588,75262,2019-04-22 14:53:02
11,광진구,11260,201704,379339,126579,2.34,110605,174332,2018-01-05 16:52:25
12,관악구,11440,201906,431423,177247,2.65,233214,192414,2018-01-05 16:52:25
13,서초구,11500,201712,234627,144805,2.46,172446,332802,2019-09-05 14:06:33
14,강남구,11380,201712,451253,63851,2.62,320480,177158,2021-06-21 11:02:17
15,강남구,11305,201904,542576,173142,2.54,60139,243251,2020-11-03 10:50:11
16,종로구,11470,201505,442119,248840,2.19,157312,61327,2019-04-22 14:53:02
17,광진구,11350,202001,226161,159500,2.08,232838,158869,2019-03-11 09:30:24
18,구로구,11410,201504,126270,172505,2.26,74025,284150,2019-08-05 09:45:14
19,노원구,11170,201412,233017,243049,2.40,117497,298131,2020-11-03 10:50:11
20,중랑구,11470,201807,421579,133458,1.99,206423,182741,2018-01-05 16:52:25
21,도봉구,11380,201408,483473,167301,2.03,225186,204424,2020-07-22 20:11:55
22,성동구,11545,201805,300410,269220,2.64,74662,197070,2018-12-05 10:20:57
23,구로구,11320,201505,305785,136393,2.62,187960,177515,2019-03-11 09:30:24
24,서초구,11440,201704,405271,135147,2.11,150937,148298,2018-11-05 09:53:36
25,강서구,11410,201712,378199,185610,2.46,157743,78354,2018-01-05 16:52:25
26,금천구,11440,202007,218929,259692,2.34,255912,285095,2018-01-05 16:52:25
27,노원구,11710,201409,373252,138984,2.23,258407,204359,2018-01-05 16:52:25
28,은평구,11170,201404,149524,229712,2.57,167155,162829,2018-01-05 16:52:25
29,노원구,11680,201708,478019,100534,2.18,278171,61187,2018-01-05 16:52:25